//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AsnUmaidEntities : DbContext
    {
        public AsnUmaidEntities()
            : base("name=AsnUmaidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressesTest> AddressesTests { get; set; }
        public virtual DbSet<BidsTest> BidsTests { get; set; }
        public virtual DbSet<CleaningLevelsTest> CleaningLevelsTests { get; set; }
        public virtual DbSet<ListingsTest> ListingsTests { get; set; }
        public virtual DbSet<PicturesTest> PicturesTests { get; set; }
        public virtual DbSet<ProfilesTest> ProfilesTests { get; set; }
        public virtual DbSet<PropertiesTest> PropertiesTests { get; set; }
        public virtual DbSet<TransactionsTest> TransactionsTests { get; set; }
        public virtual DbSet<UserLoginsTest> UserLoginsTests { get; set; }
        public virtual DbSet<UsersTest> UsersTests { get; set; }
        public virtual DbSet<UserTypesTest> UserTypesTests { get; set; }
    }
}
