//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bid()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int bidID { get; set; }
        public int userID { get; set; }
        public int listingID { get; set; }
        public double bidPrice { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime bidExpires { get; set; }
        public int isAccepted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Listing Listing { get; set; }
        public virtual User User { get; set; }
    }
}
