//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidsTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BidsTest()
        {
            this.TransactionsTests = new HashSet<TransactionsTest>();
        }
    
        public int BidID { get; set; }
        public int UserID { get; set; }
        public int ListingID { get; set; }
        public double BidPrice { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime BidExpires { get; set; }
        public int IsAccepted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionsTest> TransactionsTests { get; set; }
        public virtual ListingsTest ListingsTest { get; set; }
        public virtual UsersTest UsersTest { get; set; }
    }
}
