//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingsTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListingsTest()
        {
            this.BidsTests = new HashSet<BidsTest>();
            this.TransactionsTests = new HashSet<TransactionsTest>();
        }
    
        public int ListingID { get; set; }
        public int UserID { get; set; }
        public int PropertyID { get; set; }
        public Nullable<System.DateTime> ListingStartTime { get; set; }
        public Nullable<System.DateTime> ListingExpiryTime { get; set; }
        public Nullable<int> CleaningLevelID { get; set; }
        public string AdditionalInfo { get; set; }
        public int IsLive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidsTest> BidsTests { get; set; }
        public virtual CleaningLevelsTest CleaningLevelsTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionsTest> TransactionsTests { get; set; }
        public virtual PropertiesTest PropertiesTest { get; set; }
        public virtual UsersTest UsersTest { get; set; }
    }
}
