//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Listing()
        {
            this.Bids = new HashSet<Bid>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int listingID { get; set; }
        public int userID { get; set; }
        public int propertyID { get; set; }
        public Nullable<System.DateTime> listingStartTime { get; set; }
        public Nullable<System.DateTime> listingExpiryTime { get; set; }
        public Nullable<int> cleaningLevelID { get; set; }
        public string additionalInfo { get; set; }
        public int isLive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual CleaningLevel CleaningLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
    }
}
