//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertiesTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertiesTest()
        {
            this.AddressesTests = new HashSet<AddressesTest>();
            this.ListingsTests = new HashSet<ListingsTest>();
            this.PicturesTests = new HashSet<PicturesTest>();
        }
    
        public int PropertyID { get; set; }
        public int UserID { get; set; }
        public Nullable<double> PriceLight { get; set; }
        public Nullable<double> PriceMedium { get; set; }
        public Nullable<double> PriceHeavy { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> NumBedrooms { get; set; }
        public Nullable<int> NumBathrooms { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> IsVacant { get; set; }
        public Nullable<int> HasPets { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressesTest> AddressesTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListingsTest> ListingsTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PicturesTest> PicturesTests { get; set; }
        public virtual UsersTest UsersTest { get; set; }
    }
}
